# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Data Science For Business Analytics Project :'
tagline:          'Top Manhattan Restaurant Analysis'
description:      ''
url:              antoinefama.github.io
baseurl:          ''
paginate:         5
paginate_path:    '/blog/page:num/'


